<script>
    import { onMount } from "svelte";
    import * as d3 from "d3";
    import {
        generateGPSamples,
        kernel_Periodic
    } from '$components/generate_data_prior/auxiliares';

    let width = 800;
    let height = 400;
    let margin = { top: 20, right: 20, bottom: 40, left: 40 };
    let svg;
    let xScale, yScale;

    const start = -5;
    const end = 5;
    const numberOfPoints = 28;
    const step = (end - start) / (numberOfPoints - 1);
    const Xtest = d3.range(start, end + step / 2, step); 
    const seed = 0.5;

    let initialSamples = [];
    const kernelFunction = (x, y) => kernel_Periodic(x, y, 0.5, 1.0);

    function plotSamples() {

        const data = Xtest.map((x, i) => ({ x, y: initialSamples[i] }));
        yScale.domain([-3, 3]);

        // Pontos
        const points = svg.select('#points-group')
            .selectAll('circle')
            .data(data, d => d.x);

        points.enter()
            .append('circle')
            .attr('cx', d => xScale(d.x))
            .attr('cy', d => yScale(d.y))
            .attr('r', 4)
            .attr('fill', '#47A2A4')
            .attr('opacity', 0.8)
            .merge(points)
            .transition()
            .duration(500)
            .attr('cx', d => xScale(d.x))
            .attr('cy', d => yScale(d.y));

        points.exit().remove();
    }

    onMount(() => {
        const samples = generateGPSamples(kernelFunction, start, end, step, seed);
        initialSamples = samples.y;

        svg = d3.select('#gp-svg')
            .attr('width', width)
            .attr('height', height);

        // Borda do gráfico
        svg.append('rect')
            .attr('x', margin.left)
            .attr('y', 0)
            .attr('width', width - margin.left - margin.right)
            .attr('height', height)
            .attr('fill', 'none')
            .attr('stroke', 'black')
            .attr('stroke-width', 2)
            .attr('shape-rendering', 'crispEdges');

        // Delimitação para pontos não ficarem fora do gráfico
        svg.append("defs")
            .append("clipPath")
            .attr("id", "plot-clip")
            .append("rect")
            .attr("x", margin.left)
            .attr("y", 0)
            .attr("width", width - margin.left - margin.right)
            .attr("height", height);

        xScale = d3.scaleLinear()
            .domain([start, end])
            .range([margin.left, width - margin.right]);

        yScale = d3.scaleLinear()
            .range([height - margin.bottom, margin.top]);

        svg.append('g').attr('id', 'points-group').attr("clip-path", "url(#plot-clip)");
        svg.append('g').attr('id', 'axes-group');

        plotSamples();
    });
</script>

<div class="container">
    <h2>Prior Samples</h2>
    <svg id="gp-svg"></svg>
    <div class="explanation">
        <p>The graph shows samples of points generated by a Gaussian Process with a prior defined by a covariance function. Each point in the graph represents a value of the function sampled at a specific position of x, before any data is observed. The samples, generated from a multivariate normal distribution, reflect the model's uncertainty about the function values at different points in the input space. These points illustrate the variation of the function, given the correlation between points defined by the covariance matrix. The graph helps visualize how the GP can generate different realizations of the function based on assumptions about its structure, before real data is observed.</p>
    </div>
</div>

<style>
    @import url('https://fonts.googleapis.com/css2?family=Fredoka:wght@400;600&display=swap');

    .container {
        display: flex;
        flex-direction: column;
        align-items: center;
        font-family: 'Fredoka', sans-serif;
        width: 90%; 
        margin: 0 auto; 
    }

    h2 {
        font-size: 30px;
        text-align: center;
    }

    .explanation {
        background-color: #e5e7eb;
        border-radius: 12px;
        margin-top: 20px;
        margin-left: 20px;
        width: 100%; 
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        font-size: 16px;
        text-align: justify;
        padding: 0 15px;
        color: #333;
    }
</style>